apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoind.fullname" . }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.bitcoind.rpc.port }}
      targetPort: tcp-p2p
      protocol: TCP
      name: tcp-p2p
    - port: {{ .Values.bitcoind.rpc.rpcPort }}
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
  selector:
    {{- include "bitcoind.selectorLabels" . | nindent 4 }}
